# Builds assets/sop_index.js -- a static JS array of extracted SOP text used by the AI Trainer.
# Re-run this script any time SOP files are added or changed.

$root = $PSScriptRoot
$outFile = Join-Path $root "assets\sop_index.js"

function Get-PlainText($html) {
    $t = $html
    $t = [regex]::Replace($t, '(?is)<style.*?</style>', ' ')
    $t = [regex]::Replace($t, '(?is)<script.*?</script>', ' ')
    $t = [regex]::Replace($t, '(?is)<(br|/p|/div|/li|/h[1-6]|/tr)\s*>', "`n")
    $t = [regex]::Replace($t, '(?is)<.*?>', ' ')
    $t = [System.Net.WebUtility]::HtmlDecode($t)
    $t = [regex]::Replace($t, '[ \t]+', ' ')
    $t = [regex]::Replace($t, '\n\s*\n+', "`n")
    $t = $t.Trim()
    return $t
}

function Get-Title($html) {
    $m = [regex]::Match($html, '(?is)<title>(.*?)</title>')
    if ($m.Success) {
        $title = $m.Groups[1].Value -replace '\s*\|\s*Spectrum SOP\s*$', ''
        return [System.Net.WebUtility]::HtmlDecode($title).Trim()
    }
    return "Untitled SOP"
}

function Get-DocxText($docxPath) {
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $zip = [System.IO.Compression.ZipFile]::OpenRead($docxPath)
    try {
        $entry = $zip.GetEntry("word/document.xml")
        $reader = New-Object System.IO.StreamReader($entry.Open())
        $xml = $reader.ReadToEnd()
        $reader.Close()
    } finally {
        $zip.Dispose()
    }

    # Mark paragraph/cell breaks before stripping tags so chunks stay readable
    $xml = [regex]::Replace($xml, '</w:p>', "`n", 'IgnoreCase')
    $xml = [regex]::Replace($xml, '<w:tab/?>', "`t", 'IgnoreCase')
    $xml = [regex]::Replace($xml, '<[^>]+>', '')
    $text = [System.Net.WebUtility]::HtmlDecode($xml)
    $text = [regex]::Replace($text, '\d{7,}', ' ')
    $text = [regex]::Replace($text, '[ \t]+', ' ')
    $text = [regex]::Replace($text, '\n\s*\n+', "`n")
    return $text.Trim()
}

function Get-ManualChunks($text, $maxChars) {
    $paragraphs = $text -split "`n" | Where-Object { $_.Trim().Length -gt 0 }
    $chunks = @()
    $current = ""

    foreach ($p in $paragraphs) {
        if (($current.Length + $p.Length + 1) -gt $maxChars -and $current.Length -gt 0) {
            $chunks += $current.Trim()
            $current = ""
        }
        $current += $p + "`n"
    }
    if ($current.Trim().Length -gt 0) {
        $chunks += $current.Trim()
    }
    return $chunks
}

$docs = @()

# Employee training manual (chunked so retrieval can find the relevant section)
$manualDocx = Join-Path $root "Revised Spectrum Manual - July 2023.docx"
if (Test-Path $manualDocx) {
    $manualText = Get-DocxText $manualDocx
    $chunks = Get-ManualChunks $manualText 1800
    for ($i = 0; $i -lt $chunks.Count; $i++) {
        $docs += [PSCustomObject]@{
            id    = "Manual_Part_$($i + 1)"
            title = "Employee Training Manual - Part $($i + 1) of $($chunks.Count)"
            url   = "Revised%20Spectrum%20Manual%20-%20July%202023.pdf"
            text  = $chunks[$i]
        }
    }
    Write-Host "Extracted $($chunks.Count) manual chunks from $manualDocx"
}

# Root-level legacy SOP files
$rootFiles = @(
    "SOP_01_Answer_Hold_Transfer.html",
    "SOP_02_Message_Tickets.html",
    "SOP_03_Office_Checkout_OnCall.html"
)

foreach ($f in $rootFiles) {
    $path = Join-Path $root $f
    if (Test-Path $path) {
        $html = Get-Content $path -Raw -Encoding UTF8
        $docs += [PSCustomObject]@{
            id    = [System.IO.Path]::GetFileNameWithoutExtension($f)
            title = Get-Title $html
            url   = $f
            text  = Get-PlainText $html
        }
    }
}

# SOP_Library files
$libDir = Join-Path $root "SOP_Library"
$libFiles = Get-ChildItem $libDir -Filter "SOP*.html" | Sort-Object Name

foreach ($fi in $libFiles) {
    $html = Get-Content $fi.FullName -Raw -Encoding UTF8
    $docs += [PSCustomObject]@{
        id    = [System.IO.Path]::GetFileNameWithoutExtension($fi.Name)
        title = Get-Title $html
        url   = "SOP_Library/$($fi.Name)"
        text  = Get-PlainText $html
    }
}

$json = $docs | ConvertTo-Json -Depth 4 -Compress
$js = "// Auto-generated by build_sop_index.ps1 -- do not edit by hand.`nconst SOP_INDEX = $json;`n"

Set-Content -Path $outFile -Value $js -Encoding UTF8

Write-Host "Wrote $($docs.Count) SOP entries to $outFile"
